- hosts: "{{ host }}"
  remote_user: root
  tasks:
    - name: Set the hostname
      # hostname trick from https://garthkerr.com/meaningful-hostnames-with-ansible
      hostname:
        name: "{{ hostname.replace('*', (ansible_all_ipv4_addresses|hash('sha512'))[0:4]) }}"
    - name: Update system
      yum:
        name: '*'
        state: latest
    - name: Install yum-cron
      yum:
        name: yum-cron
        state: latest
    - name: Set yum-cron
      lineinfile:
        dest: "/etc/yum/yum-cron.conf"
        regexp: "apply_updates = no"
        line: "apply_updates = yes"
        state: present
    - name: Enable yum-cron
      systemd:
        name: yum-cron
        enabled: yes
        state: started
    - name: Add main user
      user:
        name: "{{ username }}"
        password_lock: yes # the account should only be accessible with an ssh key anyway
        state: present
    - name: Add main user to sudoers file
      lineinfile:
        dest: "/etc/sudoers"
        regexp: "{{ username }} ALL" # check if this line already exists
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
    - name: Set new sshd_config file
      copy:
        src: "./sshd_config"
        dest: "/etc/ssh/sshd_config"
        owner: root
        group: root
        mode: 0655
    - name: Authorize ssh key
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', ssh_public_key) }}"
        path: "/etc/ssh/authorized_keys/{{ username }}"
    - name: restart sshd
      systemd:
        name: sshd
        enabled: yes
        state: restarted
    - name: Lock root
      user:
        name: root
        password_lock: yes
