- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - import_tasks: "partials/container.yml"
      vars:
        container_name: "send"
        container_port: "1443"
        container_path: "send"
