- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/{{ apache_domain }}/public"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "{{ apache_domain }}"
        container_domain: "{{ apache_domain }}"
        container_port: "80"
        container_tag: "httpd:2.4"
        container_traefik: "true"
        container_env:
          UID: "{{ ansible_env['SUDO_UID'] }}"
          GID: "{{ ansible_env['SUDO_GID'] }}"
        container_volumes:
          - "{{ data_dir }}/{{ apache_domain }}:/usr/local/apache2/htdocs/:ro"
