- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data_dir directory
      file:
        state: directory
        path: "{{ data_dir }}/cryptpad/datastore"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "cryptpad"
        container_port: "3000"
        container_path: "cryptpad"
        container_traefik: "true"
        container_repo: "https://github.com/nrobinaubertin/dockerfiles.git"
        container_env:
          DOMAIN: "https://cryptpad.{{ domain }}"
          UID: "{{ ansible_env['SUDO_UID'] }}"
          GID: "{{ ansible_env['SUDO_GID'] }}"
        container_volumes:
          - "{{ data_dir }}/cryptpad/datastore:/cryptpad/datastore"
