- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/elzire.fr/data"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_repo: "https://github.com/nrobinaubertin/custom-cms.git"
        container_name: "elzire.fr"
        container_port: "8080"
        container_path: ""
        container_traefik: "true"
        container_domain: "elzire.fr,www.elzire.fr"
        container_volumes:
          - "{{ data_dir }}/elzire.fr/data:/elzire/data"
