- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "firefox_syncserver"
        container_port: "5000"
        container_path: "firefox_syncserver"
        container_domain: "firefox-syncserver.{{ domain }}"
        container_env:
          URL: "https://firefox-syncserver.{{ domain }}"
