- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "glances"
        container_port: "61208"
        container_path: "NOT_READY/glances"
        container_pid_mode: "host"
        container_env:
          CACHED_TIME: 30
          GLANCES_OPT: "--disable-process"
        container_volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
