- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/jirafeau/data"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "jirafeau"
        container_port: "8080"
        container_path: "NOT_STABLE/jirafeau"
        container_traefik: "true"
        container_repo: "https://github.com/nrobinaubertin/dockerfiles.git"
        container_env:
          DOMAIN: "https://jirafeau.{{ domain }}"
          ADMIN_PASSWORD: "{{ jirafeau_admin_password }}"
        container_volumes:
          - "{{ data_dir }}/jirafeau/data:/jirafeau/data"
