- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/prosody/data"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "prosody"
        container_port: "5280"
        container_path: "NOT_READY/prosody"
        container_env:
          DOMAIN: "{{ domain }}"
          SUBDOMAIN: "prosody"
          ADMIN: "{{ admin_email }}"
        container_volumes:
          - "{{ data_dir }}/prosody/data:/prosody/data"
        container_ports:
          - "5000:5000"
          - "5222:5222"
