- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/prosody/data"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "prosody"
        container_path: "NOT_STABLE/prosody"
        container_repo: "https://github.com/nrobinaubertin/dockerfiles.git"
        container_env:
          DOMAIN: "{{ domain }}"
          ADMIN_EMAIL: "{{ xmpp_admin_email }}"
          SSL_CERT: "/cert.pem"
          SSL_KEY: "/key.pem"
        container_volumes:
          - "{{ data_dir }}/prosody/data:/data"
          - "{{ data_dir }}/traefik/certs/certs/{{ domain }}.crt:/cert.pem:ro"
          - "{{ data_dir }}/traefik/certs/private/{{ domain }}.key:/key.pem:ro"
        container_ports:
          - "5000:5000"
          - "5222:5222"
          - "5269:5269"
          - "5280-5281:5280-5281"
          - "3478-3479:3478-3479"
          - "5349-5350:5349-5350"
          - "49152-49162:49152-49162"
