- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Install python utilities
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - python-passlib
          - python2-bcrypt
    - name: Create config directory
      file:
        state: directory
        path: "{{ data_dir }}/radicale/config"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - name: Create the htpasswd file
      htpasswd:
        create: yes
        crypt_scheme: "bcrypt"
        group: "{{ username }}"
        owner: "{{ username }}"
        path: "{{ data_dir }}/radicale/config/htpasswd"
        name: "{{ username }}"
        password: "{{ password }}"
    - name: Create collections directory
      file:
        state: directory
        path: "{{ data_dir }}/radicale/collections"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "radicale"
        container_port: "5232"
        container_path: "radicale"
        container_traefik: "true"
        container_repo: "https://github.com/nrobinaubertin/dockerfiles.git"
        container_volumes:
          - "{{ data_dir }}/radicale/config:/radicale/config"
          - "{{ data_dir }}/radicale/collections:/radicale/collections"
        container_env:
          UID: "{{ ansible_env['SUDO_UID'] }}"
          GID: "{{ ansible_env['SUDO_GID'] }}"
