- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "syncthing"
        container_port: "8384"
        container_path: "NOT_READY/syncthing"
        container_traefik: "true"
        container_env:
          UID: "{{ ansible_env['SUDO_UID'] }}"
          GID: "{{ ansible_env['SUDO_GID'] }}"
        container_volumes:
          - "{{ data_dir }}:/data"
        container_ports:
          - "22000:22000"
          - "21027:21027"
