- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/tiddlywiki/data"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "tiddlywiki"
        container_port: "8080"
        container_path: "NOT_READY/tiddlywiki"
        container_auth: "{{ username + ':' + auth_password }}"
        container_volumes:
          - "{{ data_dir }}/tiddlywiki/data:/data"
        container_env:
          UID: "{{ ansible_env['SUDO_UID'] }}"
          GID: "{{ ansible_env['SUDO_GID'] }}"
