- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create traefik data dir
      file:
        state: directory
        path: "{{ data_dir }}/traefik"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - name: Create traefik acme file
      file:
        state: touch
        path: "{{ data_dir }}/traefik/acme.json"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0600
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "traefik"
        container_ports:
          - 80:80
          - 443:443
        container_path: "NOT_STABLE/traefik"
        container_repo: "https://github.com/nrobinaubertin/dockerfiles.git"
        container_traefik: "false"
        container_env:
          UID: "{{ ansible_env['SUDO_UID'] }}"
          GID: "{{ ansible_env['SUDO_GID'] }}"
          EMAIL: "{{ admin_email }}"
        container_volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "{{ data_dir }}/traefik/:/data"
        container_networks:
          - name: "{{ network_name | default('bridge') }}"
