- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/{{ wordpress_domain }}/wp-content"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_name: "{{ wordpress_domain }}"
        container_port: "8080"
        container_path: "NOT_READY/wordpress"
        container_domain: "{{ wordpress_domain }}"
        container_env:
          DOMAIN: "{{ domain }}"
          CONTACT: "{{ admin_email }}"
        container_volumes:
          - "{{ data_dir }}/{{ wordpress_domain }}/wp-content:/wordpress/wp-content"
