- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/zus.am/data"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_repo: "https://github.com/zusam/zusam.git"
        container_repo_branch: "0.4.1"
        container_path: ""
        container_name: "zus.am"
        container_port: "8080"
        container_traefik: "true"
        container_domain: "zus.am"
        container_volumes:
          - "{{ data_dir }}/zus.am/data:/zusam/data"
        container_env:
          DOMAIN: "zus.am"
          LANG: "fr"
          ALLOW_EMAIL: "true"
          ALLOW_IMAGE_UPLOAD: "true"
          ALLOW_VIDEO_UPLOAD: "true"
