- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Create data directory
      file:
        state: directory
        path: "{{ data_dir }}/zusam/data"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - import_tasks: "../partials/container.yml"
      vars:
        container_repo: "https://github.com/nrobinaubertin/zusam.git"
        container_path: ""
        container_name: "zusam"
        container_port: "8080"
        container_traefik: "true"
        container_volumes:
          - "{{ data_dir }}/zusam/data:/zusam/data"
        container_env:
          UID: "{{ ansible_env['SUDO_UID'] }}"
          GID: "{{ ansible_env['SUDO_GID'] }}"
          INSTANCE_TYPE: "default"
          DOMAIN: "zusam.niels.fr"
