- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  vars:
    RESTIC_VERSION: "0.9.2"
    RESTIC_CHECKSUM: "sha256:1ad8a76a9f966da5f7a319c49a6db071a60ebaa24d69e6d86d53d6f2bcaf11ed"
  tasks:
    - name: Install packages
      yum:
        name: "bzip2"
        state: latest
    - name: Get restic binary
      get_url:
        checksum: "{{ RESTIC_CHECKSUM }}"
        dest: "/tmp/restic.bz2"
        force: yes
        group: "{{ username }}"
        owner: "{{ username }}"
        mode: 0755
        url: "https://github.com/restic/restic/releases/download/v{{ RESTIC_VERSION }}/restic_{{ RESTIC_VERSION }}_linux_amd64.bz2"
    - name: Extract restic binary
      shell: "bzip2 -fd /tmp/restic.bz2"
    - name: Prepare the restic binary
      shell: "mv /tmp/restic /opt/restic && chmod +x /opt/restic"
    - name: Copy backup script
      copy:
        src: "./backup.sh"
        dest: "/opt/backup.sh"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - name: Replace value in backup script
      replace:
        path: "/opt/backup.sh"
        regexp: "<B2_ACCOUNT_ID>"
        replace: "{{ b2_account_id }}"
    - name: Replace value in backup script
      replace:
        path: "/opt/backup.sh"
        regexp: "<B2_ACCOUNT_KEY>"
        replace: "{{ b2_account_key }}"
    - name: Replace value in backup script
      replace:
        path: "/opt/backup.sh"
        regexp: "<B2_BUCKET_NAME>"
        replace: "{{ b2_bucket_name }}"
    - name: Replace value in backup script
      replace:
        path: "/opt/backup.sh"
        regexp: "<RESTIC_PASSWORD>"
        replace: "{{ restic_password }}"
    - name: Replace value in backup script
      replace:
        path: "/opt/backup.sh"
        regexp: "<DATA_DIR>"
        replace: "{{ data_dir }}"
    - name: Add backup job to the cron
      cron:
        name: "restic-cloud-backup"
        disabled: no
        hour: 3
        minute: 14
        state: present
        job: "/opt/backup.sh"
