- hosts: "{{ host }}"
  remote_user: "{{ username }}"
  become: yes
  vars:
    packages:
      - git
      - python-docker-py
  tasks:
    - name: Install utilities for docker
      yum:
        name: "{{ packages }}"
        state: latest
    - name: Create traefik data dir
      file:
        state: directory
        path: "{{ data_dir }}/traefik"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
    - name: Create traefik acme file
      file:
        state: touch
        path: "{{ data_dir }}/traefik/acme.json"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0600
    - name: Clone dockerfiles repo
      git:
        repo: "https://github.com/nrobinaubertin/dockerfiles.git"
        # we don't need to keep the repository
        dest: "/tmp/git/dockerfiles"
    - name: Create image
      docker_image:
        state: present
        name: "traefik"
        path: "/tmp/git/dockerfiles/NOT_READY/traefik"
    - name: Start container
      docker_container:
        image: "traefik"
        name: "traefik"
        restart_policy: "unless-stopped"
        state: started
        env:
          EMAIL: "{{ admin_email }}"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "{{ data_dir }}/traefik/:/data"
        ports:
          - 80:80
          - 443:443
        networks:
          - name: "{{ network_name | default('bridge') }}"
